### ISSUE TITLE
npm start fails for contribution create-react-styleguide on windows

### ISSUE THREAD

**Issue by geoalexidis** [zillow/react-slider#176]
Hi,

Wanted to contribute something.

After `npm install` and `npm start` the server doesn't start

```
C:\www\react-slider [master ≡ +0 ~1 -0 !]> npm start

> react-slider@1.0.6 start C:\www\react-slider
> create-react-styleguide script start

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\www\react-slider\node_modules\.bin\styleguidist ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\www\\react-slider\\node_modules\\.bin\\styleguidist',
  path: 'C:\\www\\react-slider\\node_modules\\.bin\\styleguidist',
  spawnargs: [ 'server' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slider@1.0.6 start: `create-react-styleguide script start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slider@1.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Georgios\AppData\Roaming\npm-cache\_logs\2020-05-14T15_06_15_165Z-debug.log
```

my versions are:
```
C:\www\react-slider [master ≡ +0 ~1 -0 !]> node -v
v12.12.0
C:\www\react-slider [master ≡ +0 ~1 -0 !]> npm -v
6.11.3
```

**Comment by viters** [comment]
This is probably a Windows specific issue and can be connected with `create-react-styleguide`. Until this is resolved, you may try using WSL.

**Comment by geoalexidis** [comment]
@viters thx.

Im running it on WSL now.
